"""Initial database schema

Revision ID: 001_initial
Revises: 
Create Date: 2026-03-05 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    
    # Policy Root table
    op.create_table('policy_root',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('insurer_name', sa.String(255), nullable=False),
        sa.Column('policy_number', sa.String(100), nullable=False),
        sa.Column('jurisdiction', sa.String(10), nullable=False),
        sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
        sa.Column('effective_until', sa.DateTime(timezone=True), nullable=False),
        sa.Column('activity_classes', sa.JSON(), nullable=False, default=dict),
        sa.Column('base_limits', sa.JSON(), nullable=False, default=dict),
        sa.Column('exclusions', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, default='active'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('policy_number'),
        sa.CheckConstraint("status IN ('active', 'expired', 'suspended')", name='policy_root_status_check')
    )
    op.create_index('idx_policy_root_jurisdiction', 'policy_root', ['jurisdiction'])
    op.create_index('idx_policy_root_status', 'policy_root', ['status'])
    
    # Activity Class table
    op.create_table('activity_class',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('slug', sa.String(50), unique=True, nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('base_risk_score', sa.Numeric(3, 2), default=0.00),
        sa.Column('default_limits', sa.JSON(), nullable=True, default=dict),
        sa.Column('prohibited_equipment', sa.JSON(), nullable=True, default=dict),
        sa.Column('allows_alcohol', sa.Boolean(), default=False),
        sa.Column('allows_minors', sa.Boolean(), default=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug'),
        sa.CheckConstraint('base_risk_score >= 0.00 AND base_risk_score <= 1.00', name='activity_class_risk_score_check')
    )
    op.create_index('idx_activity_class_slug', 'activity_class', ['slug'])
    
    # Space Risk Profile table
    op.create_table('space_risk_profile',
        sa.Column('space_id', sa.String(36), nullable=False),
        sa.Column('owner_id', sa.String(100), nullable=True),
        sa.Column('name', sa.String(255), nullable=True),
        sa.Column('hazard_rating', sa.Numeric(3, 2), default=0.00),
        sa.Column('floor_type', sa.String(100)),
        sa.Column('stairs', sa.Boolean(), default=False),
        sa.Column('tools_present', sa.Boolean(), default=False),
        sa.Column('fire_suppression', sa.Boolean(), default=False),
        sa.Column('prior_claims', sa.Integer(), default=0),
        sa.Column('restrictions', sa.JSON(), nullable=True, default=dict),
        sa.Column('last_inspected_at', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now()),
        sa.PrimaryKeyConstraint('space_id'),
        sa.CheckConstraint('hazard_rating >= 0.00 AND hazard_rating <= 1.00', name='space_risk_profile_hazard_rating_check'),
        sa.CheckConstraint('prior_claims >= 0', name='space_risk_profile_prior_claims_check')
    )
    
    # Insurance Envelope table
    op.create_table('insurance_envelope',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('policy_root_id', sa.String(36), nullable=False),
        sa.Column('activity_class_id', sa.String(36), nullable=False),
        sa.Column('space_id', sa.String(36), nullable=False),
        sa.Column('steward_id', sa.String(100), nullable=False),
        sa.Column('platform_entity_id', sa.String(100), nullable=False),
        sa.Column('event_metadata', sa.JSON(), nullable=True, default=dict),
        sa.Column('attendance_cap', sa.Integer(), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('alcohol', sa.Boolean(), default=False),
        sa.Column('minors_present', sa.Boolean(), default=False),
        sa.Column('coverage_limits', sa.JSON(), nullable=True, default=dict),
        sa.Column('exclusions', sa.JSON(), nullable=True, default=dict),
        sa.Column('jurisdiction', sa.String(10), nullable=False),
        sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
        sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
        sa.Column('certificate_url', sa.String(500)),
        sa.Column('certificate_hash', sa.String(64)),
        sa.Column('status', sa.String(20), default='pending'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['policy_root_id'], ['policy_root.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['activity_class_id'], ['activity_class.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['space_id'], ['space_risk_profile.space_id'], ondelete='RESTRICT'),
        sa.CheckConstraint("status IN ('pending', 'active', 'voided', 'expired', 'claim_open')", name='insurance_envelope_status_check'),
        sa.CheckConstraint('attendance_cap > 0', name='insurance_envelope_attendance_cap_check'),
        sa.CheckConstraint('duration_minutes > 0', name='insurance_envelope_duration_minutes_check')
    )
    op.create_index('idx_insurance_envelope_status', 'insurance_envelope', ['status'])
    op.create_index('idx_insurance_envelope_validity', 'insurance_envelope', ['valid_from', 'valid_until'])
    op.create_index('idx_insurance_envelope_space', 'insurance_envelope', ['space_id'])
    op.create_index('idx_insurance_envelope_steward', 'insurance_envelope', ['steward_id'])
    op.create_index('idx_insurance_envelope_status_validity', 'insurance_envelope', ['status', 'valid_until'])
    
    # Insurance Pricing table
    op.create_table('insurance_pricing',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('envelope_id', sa.String(36), nullable=False),
        sa.Column('base_rate', sa.Numeric(10, 2), nullable=False),
        sa.Column('duration_factor', sa.Numeric(5, 2), default=1.00),
        sa.Column('attendance_factor', sa.Numeric(5, 2), default=1.00),
        sa.Column('jurisdiction_factor', sa.Numeric(5, 2), default=1.00),
        sa.Column('risk_factor', sa.Numeric(5, 2), default=1.00),
        sa.Column('final_price', sa.Numeric(10, 2), nullable=False),
        sa.Column('currency', sa.String(3), default='USD'),
        sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['envelope_id'], ['insurance_envelope.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('envelope_id'),
        sa.CheckConstraint('base_rate >= 0', name='insurance_pricing_base_rate_check'),
        sa.CheckConstraint('final_price >= 0', name='insurance_pricing_final_price_check')
    )
    op.create_index('idx_insurance_pricing_envelope', 'insurance_pricing', ['envelope_id'])
    
    # Incident Report table
    op.create_table('incident_report',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('envelope_id', sa.String(36), nullable=False),
        sa.Column('reported_by', sa.String(100), nullable=False),
        sa.Column('incident_type', sa.String(50), nullable=False),
        sa.Column('severity', sa.String(20), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('evidence_urls', sa.JSON(), nullable=True, default=dict),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['envelope_id'], ['insurance_envelope.id'], ondelete='CASCADE'),
        sa.CheckConstraint("incident_type IN ('injury', 'property', 'behavioral', 'other')", name='incident_report_type_check'),
        sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='incident_report_severity_check')
    )
    op.create_index('idx_incident_report_envelope', 'incident_report', ['envelope_id'])
    op.create_index('idx_incident_report_occurred_at', 'incident_report', ['occurred_at'])
    op.create_index('idx_incident_report_severity', 'incident_report', ['severity'])
    
    # Claim table
    op.create_table('claim',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('envelope_id', sa.String(36), nullable=False),
        sa.Column('claimant_type', sa.String(50), nullable=False),
        sa.Column('status', sa.String(20), default='opened'),
        sa.Column('payout_amount', sa.Numeric(10, 2)),
        sa.Column('insurer_reference', sa.String(100)),
        sa.Column('description', sa.Text(), default=''),
        sa.Column('review_notes', sa.Text(), default=''),
        sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('closed_at', sa.DateTime(timezone=True)),
        sa.Column('reviewed_by', sa.String(100)),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['envelope_id'], ['insurance_envelope.id'], ondelete='CASCADE'),
        sa.CheckConstraint("status IN ('opened', 'under_review', 'approved', 'denied', 'paid')", name='claim_status_check'),
        sa.CheckConstraint("claimant_type IN ('space_owner', 'participant', 'platform')", name='claim_claimant_type_check'),
        sa.CheckConstraint('payout_amount IS NULL OR payout_amount >= 0', name='claim_payout_amount_check')
    )
    op.create_index('idx_claim_envelope', 'claim', ['envelope_id'])
    op.create_index('idx_claim_status', 'claim', ['status'])
    
    # Access Grant table
    op.create_table('access_grant',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('envelope_id', sa.String(36), nullable=False),
        sa.Column('lock_id', sa.String(255), nullable=False),
        sa.Column('lock_vendor', sa.String(50), nullable=False),
        sa.Column('access_type', sa.String(20), nullable=False),
        sa.Column('access_payload', sa.JSON(), nullable=True, default=dict),
        sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
        sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
        sa.Column('attendance_cap', sa.Integer(), nullable=False),
        sa.Column('checkins_used', sa.Integer(), default=0),
        sa.Column('status', sa.String(20), default='active'),
        sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('revoked_at', sa.DateTime(timezone=True)),
        sa.Column('revoke_reason', sa.String(255)),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['envelope_id'], ['insurance_envelope.id'], ondelete='CASCADE'),
        sa.CheckConstraint("status IN ('active', 'revoked', 'expired')", name='access_grant_status_check'),
        sa.CheckConstraint("access_type IN ('qr', 'pin', 'bluetooth', 'api_unlock')", name='access_grant_type_check'),
        sa.CheckConstraint('attendance_cap > 0', name='access_grant_attendance_cap_check'),
        sa.CheckConstraint('checkins_used >= 0', name='access_grant_checkins_used_check')
    )
    op.create_index('idx_access_grant_envelope', 'access_grant', ['envelope_id'])
    op.create_index('idx_access_grant_lock', 'access_grant', ['lock_id'])
    op.create_index('idx_access_grant_validity', 'access_grant', ['valid_from', 'valid_until'])
    op.create_index('idx_access_grant_status', 'access_grant', ['status'])
    
    # Audit Log table
    op.create_table('audit_log',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('event_type', sa.String(50), nullable=False),
        sa.Column('entity_type', sa.String(50), nullable=False),
        sa.Column('entity_id', sa.String(36), nullable=False),
        sa.Column('actor_id', sa.String(100)),
        sa.Column('action', sa.String(50), nullable=False),
        sa.Column('reason', sa.Text()),
        sa.Column('metadata', sa.JSON(), nullable=True, default=dict),
        sa.Column('ip_address', sa.String(45)),
        sa.Column('user_agent', sa.String(500)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'])
    op.create_index('idx_audit_log_event_type', 'audit_log', ['event_type'])
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'])
    op.create_index('idx_audit_log_actor', 'audit_log', ['actor_id'])
    
    # User table
    op.create_table('users',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('username', sa.String(50), unique=True, nullable=False),
        sa.Column('email', sa.String(255), unique=True, nullable=False),
        sa.Column('hashed_password', sa.String(255), nullable=False),
        sa.Column('role', sa.String(50), nullable=False, default='participant'),
        sa.Column('disabled', sa.Boolean(), default=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now()),
        sa.Column('last_login_at', sa.DateTime(timezone=True)),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("role IN ('admin', 'platform_operator', 'space_owner', 'steward', 'participant')", name='user_role_check')
    )
    op.create_index('idx_users_username', 'users', ['username'])
    op.create_index('idx_users_email', 'users', ['email'])
    
    # Refresh Token table
    op.create_table('refresh_tokens',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.String(36), nullable=False),
        sa.Column('token_hash', sa.String(64), unique=True, nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('revoked', sa.Boolean(), default=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('used_at', sa.DateTime(timezone=True)),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_index('idx_refresh_tokens_user', 'refresh_tokens', ['user_id'])
    op.create_index('idx_refresh_tokens_expires', 'refresh_tokens', ['expires_at'])
    op.create_index('idx_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    op.drop_table('audit_log')
    op.drop_table('access_grant')
    op.drop_table('claim')
    op.drop_table('incident_report')
    op.drop_table('insurance_pricing')
    op.drop_table('insurance_envelope')
    op.drop_table('space_risk_profile')
    op.drop_table('activity_class')
    op.drop_table('policy_root')
    
    # ### end Alembic commands ###
